# Використовуємо базовий образ Ubuntu
FROM ubuntu:22.04

# Оновлюємо та встановлюємо необхідні пакети
RUN apt-get update && \
    apt-get install -y wget openjdk-8-jre-headless && \
    apt-get clean

# Завантажуємо UniFi Controller з офіційного сайту
RUN wget -O unifi.deb https://dl.ui.com/unifi/6.5.54/unifi_sysvinit_all.deb

# Встановлюємо UniFi Controller
RUN dpkg -i unifi.deb

# Відкриваємо порти, які використовуються UniFi Controller
EXPOSE 3478/udp 8080 8443 8880 8843 6789

# Запускаємо UniFi Controller при старті контейнера
CMD ["service", "unifi", "start"]
