---
- name: Install necessary packages
  apt:
    state: present
    update_cache: yes
    pkg:
      - curl
      - python3-pip

- name: Add an APT signing key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker-ce

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present

- name: Enabling Docker service
  service:
    name: docker
    enabled: yes
    state: started

- name: Install latest docker-compose
  pip:
    name: docker-compose
    state: present

- name: Adding users to Docker group
  user:
    name: '{{ item }}'
    groups: docker
    append: yes
  with_items:
    - "{{ admin_users }}"
    - "{{ deploy_user }}"
  when: admin_users is defined and deploy_user is defined


